model:
  max_epochs: 100

data:
  size: [96,96,96]  # Match BrainIAC pretrained model size
  batch_size: 32     # Adjust based on your GPU memory
  num_workers: 4
  csv_file: "/home/ssim0068/data/ADNI_v2/csvs/ad_train.csv"
  val_csv: "/home/ssim0068/data/ADNI_v2/csvs/ad_val.csv"
  root_dir: "/home/ssim0068/data/ADNI_v2/images_mni305"

simclrvit:
  ckpt_path: "/home/ssim0068/multimodal-AD/src/mri/BrainIAC/src/checkpoints/BrainIAC.ckpt"

optim:
  lr: 0.001           # Higher LR for linear probe
  momentum: 0.9
  weight_decay: 0.0001
  clr: "no"

logger:
  save_dir: "/home/ssim0068/multimodal-AD/src/mri/BrainIAC/src/logs/mni305"
  save_name: "cn_ad_linear_probe_mni305_batch32-{epoch:02d}-{val_auc:.2f}"
  run_name_mci: "cn_ad_mni305_linear_probe_batch32"
  project_name_mci: "cn_ad_classification"

gpu:
  visible_device: "0"

trainer:
  strategy: "ddp_find_unused_parameters_true"
  precision: "16-mixed"

train:
  freeze: "no"       # FROZEN backbone for linear probe
  finetune: "yes"      # No fine-tuning
