model:
  max_epochs: 200

data:
  size: [96,96,96]
  batch_size: 64
  num_workers: 4
  csv_file: "/media/data/divyanshu/BrainIAC_V2/data/csvs/training_dataset_info.csv"
  val_csv: "/media/data/divyanshu/BrainIAC_V2/data/csvs/validation_dataset_info.csv"
  root_dir:  "/media/data/divyanshu/BrainIAC_V2/data/images"

simclrvit:
  ckpt_path: "/media/data/divyanshu/BrainIAC_V2/checkpoints/BrainIAC.ckpt"

optim:
  lr: 0.0008
  momentum: 0.9
  weight_decay: 0.0001
  clr: "no"

logger:
  save_dir: "/media/data/divyanshu/foundation_model/Brainiac_revision/simclrvit_finetuning/frozen_downstream_checkpoints"
  save_name: "100percent_seq_tejas_cls_swinvit_0008_best-model-{epoch:02d}-{val_auc:.2f}"
  run_name: "100percent_seq_tejas_cls_swinvit_0008"
  project_name: "swinvitmae_finetune_downstream_frozen"
gpu:
  visible_device: "0" 
train: 
  freeze: "no"
  finetune: "no"
  
 