data:
  train_csv: "/media/data/divyanshu/foundation_model/Brainiac_revision/simclrvit_finetuning/seg_csvs/brats_train.csv"
  val_csv:   "/media/data/divyanshu/foundation_model/Brainiac_revision/simclrvit_finetuning/seg_csvs/brats_val.csv"


model:
  img_size:     [96, 96, 96]
  in_channels:  1
  out_channels: 1

pretrain:
  simclr_checkpoint_path: "/media/data/divyanshu/foundation_model/Brainiac_revision/checkpoints/simclr_vitb_checkpoints/brainiac_trainval32k_simclr_normandscaling_vitb_cls_normonly_biasbeforenorm_lr0005_best-model-epoch=18-train_loss=0.00.ckpt"

training:
  batch_size:             10
  num_workers:            4
  max_epochs:            100
  lr:                 5e-4
  weight_decay:       1e-4
  sw_batch_size:         2
  accumulate_grad_batches: 1
  freeze:                "yes"  # Set to "yes" to freeze ViT backbone, "no" to train end-to-end

output:
  output_dir: "/media/data/divyanshu/foundation_model/Brainiac_revision/simclrvit_finetuning/frozen_downstream_checkpoints"

logger:
  save_dir: "/media/data/divyanshu/foundation_model/Brainiac_revision/simclrvit_finetuning/frozen_downstream_checkpoints"
  save_name: "100_segmentation_simclrvit_cls_0005_best-model-{epoch:02d}-{val_dice:.2f}"
  run_name: "100_segmentation_simclrvit_cls_0005_run"
  project_name: "vit_segmentation_finetune"

gpu:
  visible_device: "0" 